# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Business-EMA
version:      1.08
version_from: EMA.pm
installdirs:  site
requires:
    Math::Business::SMA:           0.99

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
